"""added a few more columns

Revision ID: 13499d182761
Revises: d25671b7f88a
Create Date: 2021-03-11 14:47:20.495554

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '13499d182761'
down_revision = 'd25671b7f88a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('demographics', sa.Column('last_intervntion_time', sa.String(length=64), nullable=True))
    op.add_column('demographics', sa.Column('most_recent', sa.String(length=64), nullable=True))
    op.add_column('demographics', sa.Column('room', sa.String(length=64), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('demographics', 'room')
    op.drop_column('demographics', 'most_recent')
    op.drop_column('demographics', 'last_intervntion_time')
    # ### end Alembic commands ###
