"""patient flag

Revision ID: 58bd464dde3a
Revises: 85d85d4974d9
Create Date: 2021-03-12 15:20:34.316913

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '58bd464dde3a'
down_revision = '85d85d4974d9'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('demographics', schema=None) as batch_op:
        batch_op.drop_column('last_intervention_time')
        batch_op.drop_column('last_intervntion_time')

    with op.batch_alter_table('performed_intervention', schema=None) as batch_op:
        batch_op.add_column(sa.Column('patient_id', sa.Integer(), nullable=True))
        batch_op.create_foreign_key(batch_op.f('fk_performed_intervention_patient_id_demographics'), 'demographics', ['patient_id'], ['id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('performed_intervention', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('fk_performed_intervention_patient_id_demographics'), type_='foreignkey')
        batch_op.drop_column('patient_id')

    with op.batch_alter_table('demographics', schema=None) as batch_op:
        batch_op.add_column(sa.Column('last_intervntion_time', sa.VARCHAR(length=64), nullable=True))
        batch_op.add_column(sa.Column('last_intervention_time', sa.VARCHAR(length=64), nullable=True))

    # ### end Alembic commands ###
