"""new user table

Revision ID: 732bf3387c8d
Revises: a49abc0c7d0d
Create Date: 2021-03-04 17:57:50.901015

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '732bf3387c8d'
down_revision = 'a49abc0c7d0d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('user',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('friendly', sa.String(length=64), nullable=True),
    sa.Column('salt', sa.String(length=128), nullable=True),
    sa.Column('password_hash', sa.String(length=128), nullable=True),
    sa.Column('user_type', sa.String(length=32), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('user')
    # ### end Alembic commands ###
