"""integers for time since last

Revision ID: 85d85d4974d9
Revises: 13499d182761
Create Date: 2021-03-11 15:53:13.445444

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '85d85d4974d9'
down_revision = '13499d182761'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('demographics', sa.Column('mins_since_last', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('demographics', 'mins_since_last')
    # ### end Alembic commands ###
