"""empty message

Revision ID: 9a499f9b8f44
Revises: 2065ccb699f0
Create Date: 2021-02-26 19:19:04.488837

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '9a499f9b8f44'
down_revision = '2065ccb699f0'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('performed_intervention',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('type', sa.Integer(), nullable=True),
    sa.Column('worker', sa.String(length=64), nullable=True),
    sa.Column('time', sa.DateTime(), nullable=True),
    sa.Column('direction', sa.String(length=64), nullable=True),
    sa.Column('pain_level', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['type'], ['intervention_type.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_performed_intervention_direction'), 'performed_intervention', ['direction'], unique=False)
    op.create_index(op.f('ix_performed_intervention_time'), 'performed_intervention', ['time'], unique=False)
    op.create_index(op.f('ix_performed_intervention_worker'), 'performed_intervention', ['worker'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_performed_intervention_worker'), table_name='performed_intervention')
    op.drop_index(op.f('ix_performed_intervention_time'), table_name='performed_intervention')
    op.drop_index(op.f('ix_performed_intervention_direction'), table_name='performed_intervention')
    op.drop_table('performed_intervention')
    # ### end Alembic commands ###
