"""empty message

Revision ID: a49abc0c7d0d
Revises: 9a499f9b8f44
Create Date: 2021-02-26 19:32:43.960790

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a49abc0c7d0d'
down_revision = '9a499f9b8f44'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index(op.f('ix_intervention_type_name'), 'intervention_type', ['name'], unique=True)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_intervention_type_name'), table_name='intervention_type')
    # ### end Alembic commands ###
