"""intervention new columns

Revision ID: a53bfdfc0a8f
Revises: 732bf3387c8d
Create Date: 2021-03-10 16:37:01.653604

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a53bfdfc0a8f'
down_revision = '732bf3387c8d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('performed_intervention', sa.Column('intervention_location', sa.String(length=64), nullable=True))
    op.add_column('performed_intervention', sa.Column('pain_location', sa.String(length=64), nullable=True))
    op.add_column('performed_intervention', sa.Column('pu_concern', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('performed_intervention', 'pu_concern')
    op.drop_column('performed_intervention', 'pain_location')
    op.drop_column('performed_intervention', 'intervention_location')
    # ### end Alembic commands ###
