"""add prevention plan column

Revision ID: d25671b7f88a
Revises: 5aa534afb791
Create Date: 2021-03-11 14:37:27.895092

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd25671b7f88a'
down_revision = '5aa534afb791'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('demographics', sa.Column('prevention_plan', sa.String(length=128), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('demographics', 'prevention_plan')
    # ### end Alembic commands ###
