"""add demographics table

Revision ID: f8c2163a1be0
Revises: a53bfdfc0a8f
Create Date: 2021-03-11 14:10:56.679219

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f8c2163a1be0'
down_revision = 'a53bfdfc0a8f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('demographics',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('admission_date', sa.DateTime(), nullable=True),
    sa.Column('age', sa.Integer(), nullable=True),
    sa.Column('braden_score', sa.Integer(), nullable=True),
    sa.Column('diagnoses', sa.String(length=128), nullable=True),
    sa.Column('medications', sa.String(length=128), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_demographics_admission_date'), 'demographics', ['admission_date'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_demographics_admission_date'), table_name='demographics')
    op.drop_table('demographics')
    # ### end Alembic commands ###
